#!/usr/bin/env python3
"""Builds the word-prediction dictionaries for the encoder keyboard (ui-encoder/Dictionary.h).

Input: frequency lists in the FrequencyWords format ("word count" per line, most frequent first),
e.g. https://github.com/hermitdave/FrequencyWords content/2018/bg/bg_50k.txt and en/en_50k.txt
(word lists derived from OpenSubtitles 2018, CC-BY-SA-4.0).

  python3 gen_dict.py bg_50k.txt en_50k.txt > ../Dictionary.h

Words are stored lowercase, most frequent first, NUL separated, with an extra NUL at the end.
Cyrillic а..я is stored as one byte 0xE0..0xFF (the CP1251 positions) to halve the flash size,
Latin a..z as ASCII.
"""
import re
import sys

BG_WORDS = 6000
EN_WORDS = 4000
MIN_LEN = 2

# rude words are dropped so that they are never offered as a completion
BLOCK_STEMS = {
    "bg": ["еба", "ебе", "ебан", "шиба", "шибан", "путк", "курв", "педера", "пичк", "хуй", "мамицата", "лайн", "гъз"],
    "en": ["fuck", "shit", "bitch", "cunt", "asshole", "motherf", "nigg", "fag", "whore", "slut", "dick", "pussy",
           "cock", "bastard", "bullshit", "goddamn", "piss", "tits"],
}
# English contraction stubs ("don" from "don't") are not words on their own
EN_STUBS = {"don", "doesn", "didn", "isn", "wasn", "aren", "couldn", "wouldn", "shouldn", "haven", "hasn",
            "weren", "ain", "ll", "ve", "re", "em"}

BG_RE = re.compile(r"^[а-я]+$")
EN_RE = re.compile(r"^[a-z]+$")


def load(path, lang, limit):
    words = []
    seen = set()
    with open(path, encoding="utf-8") as f:
        for line in f:
            parts = line.split()
            if not parts:
                continue
            w = parts[0].lower()
            if len(w) < MIN_LEN or w in seen:
                continue
            if lang == "bg":
                if not BG_RE.match(w) or any(c in w for c in "ыэё"):   # Russian-only letters
                    continue
            else:
                if not EN_RE.match(w) or w in EN_STUBS:
                    continue
            if any(w.startswith(s) for s in BLOCK_STEMS[lang]):
                continue
            seen.add(w)
            words.append(w)
            if len(words) >= limit:
                break
    return words


def encode(w):
    out = []
    for c in w:
        cp = ord(c)
        if 0x430 <= cp <= 0x44F:
            out.append("\\x%02x" % (0xE0 + cp - 0x430))
        else:
            out.append(c)
    return "".join(out)


def emit(name, words):
    size = sum(len(w) + 1 for w in words) + 1
    print("// %d words, %d bytes" % (len(words), size))
    print("static const char %s[] =" % name)
    line = "  "
    for w in words:
        lit = '"%s\\0"' % encode(w)
        if len(line) + len(lit) > 118:
            print(line.rstrip())
            line = "  "
        line += lit + " "
    print(line.rstrip())
    print('  "";')
    print()


def main():
    bg = load(sys.argv[1], "bg", BG_WORDS)
    en = load(sys.argv[2], "en", EN_WORDS)
    print("#pragma once")
    print()
    print("// Generated by tools/gen_dict.py, do not edit by hand.")
    print("// Word frequencies: FrequencyWords by Hermit Dave (OpenSubtitles 2018), CC-BY-SA-4.0,")
    print("// https://github.com/hermitdave/FrequencyWords")
    print("// Lowercase words, most frequent first, NUL separated; the list ends with an empty word.")
    print("// Cyrillic a..ya are single bytes 0xE0..0xFF (CP1251 positions), Latin is ASCII.")
    print()
    emit("DICT_BG", bg)
    emit("DICT_EN", en)


if __name__ == "__main__":
    main()
